name: "Maíra Canal"
description: "Blogging about graphics development whenever I can"
domain: "mairacanal.github.io"
url: "https://mairacanal.github.io" # Domain Name of host. [username].github.io for github pages

permalink: pretty

dark_scheme: catppuccin-frappe
light_scheme: catppuccin-frappe
# printing_scheme: tomorrow # Must have #FFFFFF background

plugins:
  - jekyll-target-blank

target-blank:
  add_css_classes: external

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

source: _src

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      nav_current: "/blog/"
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      language: "en"
      author: "Maíra Canal"
